export default [
  { tag: 'is-button', title: 'Button', category: 'actions', script: '../components/actions/button.js', style: '../components/actions/button.css', page: 'is-button.html' },
  { tag: 'is-button-group', title: 'Button Group', category: 'actions', script: '../components/actions/button-group.js', style: '../components/actions/button-group.css', page: 'is-button-group.html' },
  { tag: 'is-copy-button', title: 'Copy Button', category: 'actions', script: '../components/actions/copy-button.js', style: '../components/actions/copy-button.css', page: 'is-copy-button.html' },
  { tag: 'is-check-icon-button', title: 'Check Icon Button', category: 'actions', script: '../components/actions/check-icon-button.js', style: '../components/actions/check-icon-button.css', page: 'is-check-icon-button.html' },
  { tag: 'is-dropdown', title: 'Dropdown', category: 'actions', script: '../components/actions/dropdown.js', style: '../components/actions/dropdown.css', page: 'is-dropdown.html' },
  { tag: 'is-dropdown-item', title: 'Dropdown Item', category: 'actions', script: '../components/actions/dropdown-item.js', style: '../components/actions/dropdown-item.css', page: 'is-dropdown.html' },
  { tag: 'is-icon', title: 'Icon', category: 'media', script: '../components/media/icon.js', style: '../components/media/icon.css', page: 'is-icon.html' },
  { tag: 'is-avatar', title: 'Avatar', category: 'media', script: '../components/media/avatar.js', style: '../components/media/avatar.css', page: 'is-avatar.html' },
  { tag: 'is-video', title: 'Video', category: 'media', script: '../components/media/video.js', style: '../components/media/video.css', page: 'is-video.html' },
  { tag: 'is-video-playlist', title: 'Video Playlist', category: 'media', script: '../components/media/video-playlist.js', style: '../components/media/video-playlist.css', page: 'is-video-playlist.html' },
  { tag: 'is-spinner', title: 'Spinner', category: 'feedback', script: '../components/feedback/spinner.js', style: '../components/feedback/spinner.css', page: 'is-spinner.html' },
  { tag: 'is-badge', title: 'Badge', category: 'feedback', script: '../components/feedback/badge.js', style: '../components/feedback/badge.css', page: 'is-badge.html' },
  { tag: 'is-tag', title: 'Tag', category: 'feedback', script: '../components/feedback/tag.js', style: '../components/feedback/tag.css', page: 'is-tag.html' },
  { tag: 'is-skeleton', title: 'Skeleton', category: 'feedback', script: '../components/feedback/skeleton.js', style: '../components/feedback/skeleton.css', page: 'is-skeleton.html' },
  { tag: 'is-progress-bar', title: 'Progress Bar', category: 'feedback', script: '../components/feedback/progress-bar.js', style: '../components/feedback/progress-bar.css', page: 'is-progress-bar.html' },
  { tag: 'is-progress-ring', title: 'Progress Ring', category: 'feedback', script: '../components/feedback/progress-ring.js', style: '../components/feedback/progress-ring.css', page: 'is-progress-ring.html' },
  { tag: 'is-theme-toggle', title: 'Theme Toggle', category: 'feedback', script: '../components/feedback/theme-toggle.js', style: '../components/feedback/theme-toggle.css', page: 'is-theme-toggle.html' },
  { tag: 'is-toast', title: 'Toast', category: 'feedback', script: '../components/feedback/toast.js', style: '../components/feedback/toast.css', page: 'is-toast.html' },
  { tag: 'is-toast-item', title: 'Toast Item', category: 'feedback', script: '../components/feedback/toast-item.js', style: '../components/feedback/toast-item.css', page: 'is-toast.html' },
  { tag: 'is-tooltip', title: 'Tooltip', category: 'feedback', script: '../components/feedback/tooltip.js', style: '../components/feedback/tooltip.css', page: 'is-tooltip.html' },
  { tag: 'is-split-panel', title: 'Panel dividido', category: 'layout', script: '../components/layout/split-panel.js', style: '../components/layout/split-panel.css', page: 'is-split-panel.html' },
  { tag: 'is-card', title: 'Card', category: 'layout', script: '../components/layout/card.js', style: '../components/layout/card.css', page: 'is-card.html' },
  { tag: 'is-divider', title: 'Divider', category: 'layout', script: '../components/layout/divider.js', style: '../components/layout/divider.css', page: 'is-divider.html' },
  { tag: 'is-popup', title: 'Popup', category: 'helpers', script: '../components/helpers/popup.js', style: '../components/helpers/popup.css', page: 'is-popup.html' },
  { tag: 'is-popover', title: 'Popover', category: 'helpers', script: '../components/helpers/popover.js', style: '../components/helpers/popover.css', page: 'is-popover.html' },
  { tag: 'is-combobox', title: 'Combobox', category: 'forms', script: '../components/forms/combobox.js', style: '../components/forms/combobox.css', page: 'is-combobox.html' },
  { tag: 'is-option', title: 'Option', category: 'forms', script: '../components/forms/option.js', style: '../components/forms/option.css', page: 'is-combobox.html' },
  { tag: 'is-file-input', title: 'File Input', category: 'forms', script: '../components/forms/file-input.js', style: '../components/forms/file-input.css', page: 'is-file-input.html' },
  { tag: 'is-date-input', title: 'Date Input', category: 'forms', script: '../components/forms/date-input.js', style: '../components/forms/date-input.css', page: 'is-date-input.html' },
  { tag: 'is-date-picker', title: 'Date Picker', category: 'forms', script: '../components/forms/date-picker.js', style: '../components/forms/date-picker.css', page: 'is-date-picker.html' },
  { tag: 'is-data-grid', title: 'Data Grid', category: 'data', script: '../components/data/data-grid.js', style: '../components/data/data-grid.css', page: 'is-data-grid.html' },
  { tag: 'is-chart', title: 'Chart', category: 'data-viz', script: '../components/charts/chart.js', style: '../components/charts/chart.css', page: 'is-chart.html' },
  { tag: 'is-bar-chart', title: 'Bar Chart', category: 'data-viz', script: '../components/charts/bar-chart.js', style: '../components/charts/bar-chart.css', page: 'is-bar-chart.html' },
  { tag: 'is-line-chart', title: 'Line Chart', category: 'data-viz', script: '../components/charts/line-chart.js', style: '../components/charts/line-chart.css', page: 'is-line-chart.html' },
  { tag: 'is-pie-chart', title: 'Pie Chart', category: 'data-viz', script: '../components/charts/pie-chart.js', style: '../components/charts/pie-chart.css', page: 'is-pie-chart.html' },
  { tag: 'is-doughnut-chart', title: 'Doughnut Chart', category: 'data-viz', script: '../components/charts/doughnut-chart.js', style: '../components/charts/doughnut-chart.css', page: 'is-doughnut-chart.html' },
  { tag: 'is-radar-chart', title: 'Radar Chart', category: 'data-viz', script: '../components/charts/radar-chart.js', style: '../components/charts/radar-chart.css', page: 'is-radar-chart.html' },
  { tag: 'is-polar-area-chart', title: 'Polar Area Chart', category: 'data-viz', script: '../components/charts/polar-area-chart.js', style: '../components/charts/polar-area-chart.css', page: 'is-polar-area-chart.html' },
  { tag: 'is-scatter-chart', title: 'Scatter Chart', category: 'data-viz', script: '../components/charts/scatter-chart.js', style: '../components/charts/scatter-chart.css', page: 'is-scatter-chart.html' },
  { tag: 'is-bubble-chart', title: 'Bubble Chart', category: 'data-viz', script: '../components/charts/bubble-chart.js', style: '../components/charts/bubble-chart.css', page: 'is-bubble-chart.html' },
  { tag: 'is-sparkline', title: 'Sparkline', category: 'data-viz', script: '../components/charts/sparkline.js', style: '../components/charts/sparkline.css', page: 'is-sparkline.html' },
  { tag: 'is-relative-time', title: 'Tiempo relativo', category: 'helpers', script: '../components/helpers/relative-time.js', style: '../components/helpers/relative-time.css', page: 'is-relative-time.html' },
  { tag: 'is-format-date', title: 'Formato de fecha', category: 'helpers', script: '../components/helpers/format-date.js', style: '../components/helpers/format-date.css', page: 'is-format-date.html' },
  { tag: 'is-format-number', title: 'Formato de número', category: 'helpers', script: '../components/helpers/format-number.js', style: '../components/helpers/format-number.css', page: 'is-format-number.html' },
  { tag: 'is-format-bytes', title: 'Formato de bytes', category: 'helpers', script: '../components/helpers/format-bytes.js', style: '../components/helpers/format-bytes.css', page: 'is-format-bytes.html' },
  { tag: 'is-intersection-observer', title: 'Observador de intersección', category: 'helpers', script: '../components/helpers/intersection-observer.js', style: '../components/helpers/intersection-observer.css', page: 'is-intersection-observer.html' },
  { tag: 'is-mutation-observer', title: 'Observador de mutación', category: 'helpers', script: '../components/helpers/mutation-observer.js', style: '../components/helpers/mutation-observer.css', page: 'is-mutation-observer.html' },
  { tag: 'is-resize-observer', title: 'Resize Observer', category: 'helpers', script: '../components/helpers/resize-observer.js', style: '../components/helpers/resize-observer.css', page: 'is-resize-observer.html' },
];
