export default [
  // isp — primitivas portadas de ISP-SvelteComponents (la librería Svelte de
  // ContaPyme). El orden del nav no sale de aquí sino de `categoryMeta` en
  // index.html, donde `isp` es la primera clave.
  { tag: 'is-accordion-group', title: 'Accordion Group', category: 'isp', origin: 'isp', script: '../../components/isp/accordion-group.js', style: '../../components/isp/accordion-group.css', page: 'isp/is-accordion-group.html' },
  { tag: 'is-block-layout', title: 'Block Layout', category: 'isp', origin: 'isp', script: '../../components/isp/block-layout.js', style: '../../components/isp/block-layout.css', page: 'isp/is-block-layout.html' },
  { tag: 'is-btn-ref', title: 'Btn Ref', category: 'isp', origin: 'isp', script: '../../components/isp/btn-ref.js', style: '../../components/isp/btn-ref.css', page: 'isp/is-btn-ref.html' },
  { tag: 'is-catalogo-gen', title: 'Catálogo Gen', category: 'isp', origin: 'isp', script: '../../components/isp/catalogo-gen.js', style: '../../components/isp/catalogo-gen.css', page: 'isp/is-catalogo-gen.html' },
  { tag: 'is-confirm-delete', title: 'Confirm Delete', category: 'isp', origin: 'isp', script: '../../components/isp/confirm-delete.js', style: '../../components/isp/confirm-delete.css', page: 'isp/is-confirm-delete.html' },
  { tag: 'is-flex-layout', title: 'Flex Layout', category: 'isp', origin: 'isp', script: '../../components/isp/flex-layout.js', style: '../../components/isp/flex-layout.css', page: 'isp/is-flex-layout.html' },
  { tag: 'is-form', title: 'Form', category: 'isp', origin: 'isp', script: '../../components/isp/form.js', style: '../../components/isp/form.css', page: 'isp/is-form.html' },
  { tag: 'is-function-form', title: 'Function Form', category: 'isp', origin: 'isp', script: '../../components/isp/function-form.js', style: '../../components/isp/function-form.css', page: 'isp/is-function-form.html' },
  { tag: 'is-modal-verificacion', title: 'Modal Verificación', category: 'isp', origin: 'isp', script: '../../components/isp/modal-verificacion.js', style: '../../components/isp/modal-verificacion.css', page: 'isp/is-modal-verificacion.html' },
  { tag: 'is-grid-layout', title: 'Grid Layout', category: 'isp', origin: 'isp', script: '../../components/isp/grid-layout.js', style: '../../components/isp/grid-layout.css', page: 'isp/is-grid-layout.html' },
  { tag: 'is-heading', title: 'Heading', category: 'isp', origin: 'isp', script: '../../components/isp/heading.js', style: '../../components/isp/heading.css', page: 'isp/is-heading.html' },
  { tag: 'is-loading-overlay', title: 'Loading Overlay', category: 'isp', origin: 'isp', script: '../../components/isp/loading-overlay.js', style: '../../components/isp/loading-overlay.css', page: 'isp/is-loading-overlay.html' },
  { tag: 'is-text', title: 'Text', category: 'isp', origin: 'isp', script: '../../components/isp/text.js', style: '../../components/isp/text.css', page: 'isp/is-text.html' },
  { tag: 'is-button', title: 'Button', category: 'actions', script: '../../components/actions/button.js', style: '../../components/actions/button.css', page: 'actions/is-button.html' },
  { tag: 'is-button-group', title: 'Button Group', category: 'actions', script: '../../components/actions/button-group.js', style: '../../components/actions/button-group.css', page: 'actions/is-button-group.html' },
  { tag: 'is-copy-button', title: 'Copy Button', category: 'actions', script: '../../components/actions/copy-button.js', style: '../../components/actions/copy-button.css', page: 'actions/is-copy-button.html' },
  { tag: 'is-check-icon-button', title: 'Check Icon Button', category: 'actions', script: '../../components/actions/check-icon-button.js', style: '../../components/actions/check-icon-button.css', page: 'actions/is-check-icon-button.html' },
  { tag: 'is-dropdown', title: 'Dropdown', category: 'actions', script: '../../components/actions/dropdown.js', style: '../../components/actions/dropdown.css', page: 'actions/is-dropdown.html' },
  { tag: 'is-dropdown-item', title: 'Dropdown Item', category: 'actions', script: '../../components/actions/dropdown-item.js', style: '../../components/actions/dropdown-item.css', page: 'actions/is-dropdown-item.html' },
  { tag: 'is-icon', title: 'Icon', category: 'media', script: '../../components/media/icon.js', style: '../../components/media/icon.css', page: 'media/is-icon.html' },
  { tag: 'is-avatar', title: 'Avatar', category: 'media', script: '../../components/media/avatar.js', style: '../../components/media/avatar.css', page: 'media/is-avatar.html' },
  { tag: 'is-video', title: 'Video', category: 'media', script: '../../components/media/video.js', style: '../../components/media/video.css', page: 'media/is-video.html' },
  { tag: 'is-video-playlist', title: 'Video Playlist', category: 'media', script: '../../components/media/video-playlist.js', style: '../../components/media/video-playlist.css', page: 'media/is-video-playlist.html' },
  { tag: 'is-spinner', title: 'Spinner', category: 'feedback', script: '../../components/feedback/spinner.js', style: '../../components/feedback/spinner.css', page: 'feedback/is-spinner.html' },
  { tag: 'is-badge', title: 'Badge', category: 'feedback', script: '../../components/feedback/badge.js', style: '../../components/feedback/badge.css', page: 'feedback/is-badge.html' },
  { tag: 'is-tag', title: 'Tag', category: 'feedback', script: '../../components/feedback/tag.js', style: '../../components/feedback/tag.css', page: 'feedback/is-tag.html' },
  { tag: 'is-skeleton', title: 'Skeleton', category: 'feedback', script: '../../components/feedback/skeleton.js', style: '../../components/feedback/skeleton.css', page: 'feedback/is-skeleton.html' },
  { tag: 'is-progress-bar', title: 'Progress Bar', category: 'feedback', script: '../../components/feedback/progress-bar.js', style: '../../components/feedback/progress-bar.css', page: 'feedback/is-progress-bar.html' },
  { tag: 'is-progress-ring', title: 'Progress Ring', category: 'feedback', script: '../../components/feedback/progress-ring.js', style: '../../components/feedback/progress-ring.css', page: 'feedback/is-progress-ring.html' },
  { tag: 'is-theme-toggle', title: 'Theme Toggle', category: 'feedback', script: '../../components/feedback/theme-toggle.js', style: '../../components/feedback/theme-toggle.css', page: 'feedback/is-theme-toggle.html' },
  { tag: 'is-toast', title: 'Toast', category: 'feedback', script: '../../components/feedback/toast.js', style: '../../components/feedback/toast.css', page: 'feedback/is-toast.html' },
  { tag: 'is-toast-item', title: 'Toast Item', category: 'feedback', script: '../../components/feedback/toast-item.js', style: '../../components/feedback/toast-item.css', page: 'feedback/is-toast-item.html' },
  { tag: 'is-tooltip', title: 'Tooltip', category: 'feedback', script: '../../components/feedback/tooltip.js', style: '../../components/feedback/tooltip.css', page: 'feedback/is-tooltip.html' },
  { tag: 'is-cdn-snippet', title: 'CDN Snippet', category: 'feedback', script: '../../components/feedback/cdn-snippet.js', style: '../../components/feedback/cdn-snippet.css', page: 'feedback/is-cdn-snippet.html' },
  { tag: 'is-split-panel', title: 'Panel dividido', category: 'layout', script: '../../components/layout/split-panel.js', style: '../../components/layout/split-panel.css', page: 'layout/is-split-panel.html' },
  { tag: 'is-main', title: 'Main', category: 'layout', script: '../../components/layout/main.js', style: '../../components/layout/main.css', page: 'layout/is-main.html' },
  { tag: 'is-card', title: 'Card', category: 'layout', script: '../../components/layout/card.js', style: '../../components/layout/card.css', page: 'layout/is-card.html' },
  { tag: 'is-callout', title: 'Callout', category: 'layout', script: '../../components/layout/callout.js', style: '../../components/layout/callout.css', page: 'layout/is-callout.html' },
  { tag: 'is-details', title: 'Details', category: 'layout', script: '../../components/layout/details.js', style: '../../components/layout/details.css', page: 'layout/is-details.html' },
  { tag: 'is-dialog', title: 'Dialog', category: 'layout', script: '../../components/layout/dialog.js', style: '../../components/layout/dialog.css', page: 'layout/is-dialog.html' },
  { tag: 'is-drawer', title: 'Drawer', category: 'layout', script: '../../components/layout/drawer.js', style: '../../components/layout/drawer.css', page: 'layout/is-drawer.html' },
  { tag: 'is-divider', title: 'Divider', category: 'layout', script: '../../components/layout/divider.js', style: '../../components/layout/divider.css', page: 'layout/is-divider.html' },
  { tag: 'is-scrollspy', title: 'Scrollspy', category: 'layout', script: '../../components/layout/scrollspy.js', style: '../../components/layout/scrollspy.css', page: 'layout/is-scrollspy.html' },
  { tag: 'is-demo', title: 'Demo', category: 'layout', script: '../../components/layout/demo.js' },
  { tag: 'is-popover', title: 'Popover', category: 'helpers', script: '../../components/helpers/popover.js', style: '../../components/helpers/popover.css', page: 'helpers/is-popover.html' },
  { tag: 'is-breadcrumb', title: 'Breadcrumb', category: 'navigation', script: '../../components/navigation/breadcrumb.js', style: '../../components/navigation/breadcrumb.css', page: 'navigation/is-breadcrumb.html' },
  { tag: 'is-breadcrumb-item', title: 'Breadcrumb Item', category: 'navigation', script: '../../components/navigation/breadcrumb-item.js', style: '../../components/navigation/breadcrumb-item.css', page: 'navigation/is-breadcrumb-item.html' },
  { tag: 'is-tab-group', title: 'Tab Group', category: 'navigation', script: '../../components/navigation/tab-group.js', style: '../../components/navigation/tab-group.css', page: 'navigation/is-tab-group.html' },
  { tag: 'is-tab', title: 'Tab', category: 'navigation', script: '../../components/navigation/tab-group.js', style: '../../components/navigation/tab-group.css', page: 'navigation/is-tab.html' },
  { tag: 'is-tab-panel', title: 'Tab Panel', category: 'navigation', script: '../../components/navigation/tab-group.js', style: '../../components/navigation/tab-group.css', page: 'navigation/is-tab-panel.html' },
  { tag: 'is-scroller', title: 'Scroller', category: 'navigation', script: '../../components/navigation/scroller.js', style: '../../components/navigation/scroller.css', page: 'navigation/is-scroller.html' },
  { tag: 'is-carousel', title: 'Carousel', category: 'navigation', script: '../../components/navigation/carousel.js', style: '../../components/navigation/carousel.css', page: 'navigation/is-carousel.html' },
  { tag: 'is-carousel-item', title: 'Carousel Item', category: 'navigation', script: '../../components/navigation/carousel.js', style: '../../components/navigation/carousel.css', page: 'navigation/is-carousel-item.html' },
  { tag: 'is-tree', title: 'Tree', category: 'navigation', script: '../../components/navigation/tree.js', style: '../../components/navigation/tree.css', page: 'navigation/is-tree.html' },
  { tag: 'is-tree-item', title: 'Tree Item', category: 'navigation', script: '../../components/navigation/tree.js', style: '../../components/navigation/tree.css', page: 'navigation/is-tree-item.html' },
  { tag: 'is-stepper', title: 'Stepper', category: 'navigation', script: '../../components/navigation/stepper.js', style: '../../components/navigation/stepper.css', page: 'navigation/is-stepper.html' },
  { tag: 'is-stepper-step', title: 'Stepper Step', category: 'navigation', script: '../../components/navigation/stepper.js', style: '../../components/navigation/stepper.css', page: 'navigation/is-stepper-step.html' },
  { tag: 'is-combobox', title: 'Combobox', category: 'forms', script: '../../components/forms/combobox.js', style: '../../components/forms/combobox.css', page: 'forms/is-combobox.html' },
  { tag: 'is-option', title: 'Option', category: 'forms', script: '../../components/forms/option.js', style: '../../components/forms/option.css', page: 'forms/is-option.html' },
  { tag: 'is-checkbox', title: 'Checkbox', category: 'forms', script: '../../components/forms/checkbox.js', style: '../../components/forms/checkbox.css', page: 'forms/is-checkbox.html' },
  { tag: 'is-switch', title: 'Switch', category: 'forms', script: '../../components/forms/switch.js', style: '../../components/forms/switch.css', page: 'forms/is-switch.html' },
  { tag: 'is-radio-group', title: 'Radio Group', category: 'forms', script: '../../components/forms/radio-group.js', style: '../../components/forms/radio-group.css', page: 'forms/is-radio-group.html' },
  { tag: 'is-radio', title: 'Radio', category: 'forms', script: '../../components/forms/radio.js', style: '../../components/forms/radio.css', page: 'forms/is-radio.html' },
  { tag: 'is-input', title: 'Input', category: 'forms', script: '../../components/forms/input.js', style: '../../components/forms/input.css', page: 'forms/is-input.html' },
  { tag: 'is-textarea', title: 'Textarea', category: 'forms', script: '../../components/forms/textarea.js', style: '../../components/forms/textarea.css', page: 'forms/is-textarea.html' },
  { tag: 'is-slider', title: 'Slider', category: 'forms', script: '../../components/forms/slider.js', style: '../../components/forms/slider.css', page: 'forms/is-slider.html' },
  { tag: 'is-rating', title: 'Rating', category: 'forms', script: '../../components/forms/rating.js', style: '../../components/forms/rating.css', page: 'forms/is-rating.html' },
  { tag: 'is-select', title: 'Select', category: 'forms', script: '../../components/forms/select.js', style: '../../components/forms/select.css', page: 'forms/is-select.html' },
  { tag: 'is-color-picker', title: 'Color Picker', category: 'forms', script: '../../components/forms/color-picker.js', style: '../../components/forms/color-picker.css', page: 'forms/is-color-picker.html' },
  { tag: 'is-file-input', title: 'File Input', category: 'forms', script: '../../components/forms/file-input.js', style: '../../components/forms/file-input.css', page: 'forms/is-file-input.html' },
  { tag: 'is-date-picker', title: 'Date Picker', category: 'forms', script: '../../components/forms/date-picker.js', style: '../../components/forms/date-picker.css', page: 'forms/is-date-picker.html' },
  { tag: 'is-month-calendar', title: 'Month Calendar', category: 'forms', script: '../../components/forms/month-calendar.js', style: '../../components/forms/month-calendar.css', page: 'forms/is-month-calendar.html' },
  { tag: 'is-year-calendar', title: 'Year Calendar', category: 'forms', script: '../../components/forms/year-calendar.js', style: '../../components/forms/year-calendar.css', page: 'forms/is-year-calendar.html' },
  { tag: 'is-date-range-picker', title: 'Date Range Picker', category: 'forms', script: '../../components/forms/date-range-picker.js', style: '../../components/forms/date-range-picker.css', page: 'forms/is-date-range-picker.html' },
  { tag: 'is-time-clock', title: 'Time Clock', category: 'forms', script: '../../components/forms/time-clock.js', style: '../../components/forms/time-clock.css', page: 'forms/is-time-clock.html' },
  { tag: 'is-digital-clock', title: 'Digital Clock', category: 'forms', script: '../../components/forms/digital-clock.js', style: '../../components/forms/digital-clock.css', page: 'forms/is-digital-clock.html' },
  { tag: 'is-date-field', title: 'Date Field', category: 'forms', script: '../../components/forms/date-field.js', style: '../../components/forms/date-field.css', page: 'forms/is-date-field.html' },
  { tag: 'is-time-field', title: 'Time Field', category: 'forms', script: '../../components/forms/time-field.js', style: '../../components/forms/time-field.css', page: 'forms/is-time-field.html' },
  { tag: 'is-date-time-field', title: 'Date Time Field', category: 'forms', script: '../../components/forms/date-time-field.js', style: '../../components/forms/date-time-field.css', page: 'forms/is-date-time-field.html' },
  { tag: 'is-date-input', title: 'Date Input', category: 'forms', script: '../../components/forms/date-input.js', style: '../../components/forms/date-input.css', page: 'forms/is-date-input.html' },
  { tag: 'is-time-input', title: 'Time Input', category: 'forms', script: '../../components/forms/time-input.js', style: '../../components/forms/time-input.css', page: 'forms/is-time-input.html' },
  { tag: 'is-date-time-input', title: 'Date Time Input', category: 'forms', script: '../../components/forms/date-time-input.js', style: '../../components/forms/date-time-input.css', page: 'forms/is-date-time-input.html' },
  { tag: 'is-date-range-input', title: 'Date Range Input', category: 'forms', script: '../../components/forms/date-range-input.js', style: '../../components/forms/date-range-input.css', page: 'forms/is-date-range-input.html' },
  { tag: 'is-data-grid', title: 'Data Grid', category: 'data', script: '../../components/data/data-grid.js', style: '../../components/data/data-grid.css', page: 'data/is-data-grid.html' },
  { tag: 'is-chart', title: 'Chart', category: 'data-viz', script: '../../components/charts/chart.js', style: '../../components/charts/chart.css', page: 'data-viz/is-chart.html' },
  { tag: 'is-bar-chart', title: 'Bar Chart', category: 'data-viz', script: '../../components/charts/bar-chart.js', style: '../../components/charts/bar-chart.css', page: 'data-viz/is-bar-chart.html' },
  { tag: 'is-line-chart', title: 'Line Chart', category: 'data-viz', script: '../../components/charts/line-chart.js', style: '../../components/charts/line-chart.css', page: 'data-viz/is-line-chart.html' },
  { tag: 'is-pie-chart', title: 'Pie Chart', category: 'data-viz', script: '../../components/charts/pie-chart.js', style: '../../components/charts/pie-chart.css', page: 'data-viz/is-pie-chart.html' },
  { tag: 'is-doughnut-chart', title: 'Doughnut Chart', category: 'data-viz', script: '../../components/charts/doughnut-chart.js', style: '../../components/charts/doughnut-chart.css', page: 'data-viz/is-doughnut-chart.html' },
  { tag: 'is-radar-chart', title: 'Radar Chart', category: 'data-viz', script: '../../components/charts/radar-chart.js', style: '../../components/charts/radar-chart.css', page: 'data-viz/is-radar-chart.html' },
  { tag: 'is-polar-area-chart', title: 'Polar Area Chart', category: 'data-viz', script: '../../components/charts/polar-area-chart.js', style: '../../components/charts/polar-area-chart.css', page: 'data-viz/is-polar-area-chart.html' },
  { tag: 'is-scatter-chart', title: 'Scatter Chart', category: 'data-viz', script: '../../components/charts/scatter-chart.js', style: '../../components/charts/scatter-chart.css', page: 'data-viz/is-scatter-chart.html' },
  { tag: 'is-bubble-chart', title: 'Bubble Chart', category: 'data-viz', script: '../../components/charts/bubble-chart.js', style: '../../components/charts/bubble-chart.css', page: 'data-viz/is-bubble-chart.html' },
  { tag: 'is-sparkline', title: 'Sparkline', category: 'data-viz', script: '../../components/charts/sparkline.js', style: '../../components/charts/sparkline.css', page: 'data-viz/is-sparkline.html' },
  { tag: 'is-flowchart', title: 'Diagrama de flujo', category: 'diagrams', script: '../../components/diagrams/flowchart.js', style: '../../components/diagrams/flowchart.css', page: 'diagrams/is-flowchart.html' },
  { tag: 'is-sequence-diagram', title: 'Diagrama de secuencia', category: 'diagrams', script: '../../components/diagrams/sequence-diagram.js', style: '../../components/diagrams/sequence-diagram.css', page: 'diagrams/is-sequence-diagram.html' },
  { tag: 'is-lightbox', title: 'Lightbox', category: 'helpers', script: '../../components/diagrams/lightbox.js', style: '../../components/diagrams/lightbox.css', page: 'helpers/is-lightbox.html' },
  { tag: 'is-diagram-lightbox', title: 'Visor de diagramas', category: 'diagrams', script: '../../components/diagrams/diagram-lightbox.js', style: '../../components/diagrams/diagram-lightbox.css', page: 'diagrams/is-diagram-lightbox.html' },
  { tag: 'is-relative-time', title: 'Tiempo relativo', category: 'helpers', script: '../../components/helpers/relative-time.js', style: '../../components/helpers/relative-time.css', page: 'helpers/is-relative-time.html' },
  { tag: 'is-format', title: 'Formato', category: 'helpers', script: '../../components/helpers/format.js', style: '../../components/helpers/format.css', page: 'helpers/is-format.html' },
  { tag: 'is-observer', title: 'Observer', category: 'helpers', script: '../../components/helpers/observer.js', style: '../../components/helpers/observer.css', page: 'helpers/is-observer.html' },
  { tag: 'is-format-date', title: 'Formato de fecha', category: 'helpers', script: '../../components/helpers/format-date.js', style: '../../components/helpers/format-date.css', page: 'helpers/is-format-date.html' },
  { tag: 'is-format-number', title: 'Formato de número', category: 'helpers', script: '../../components/helpers/format-number.js', style: '../../components/helpers/format-number.css', page: 'helpers/is-format-number.html' },
  { tag: 'is-format-bytes', title: 'Formato de bytes', category: 'helpers', script: '../../components/helpers/format-bytes.js', style: '../../components/helpers/format-bytes.css', page: 'helpers/is-format-bytes.html' },
  { tag: 'is-intersection-observer', title: 'Observador de intersección', category: 'helpers', script: '../../components/helpers/intersection-observer.js', style: '../../components/helpers/intersection-observer.css', page: 'helpers/is-intersection-observer.html' },
  { tag: 'is-mutation-observer', title: 'Observador de mutación', category: 'helpers', script: '../../components/helpers/mutation-observer.js', style: '../../components/helpers/mutation-observer.css', page: 'helpers/is-mutation-observer.html' },
  { tag: 'is-resize-observer', title: 'Resize Observer', category: 'helpers', script: '../../components/helpers/resize-observer.js', style: '../../components/helpers/resize-observer.css', page: 'helpers/is-resize-observer.html' },
  { tag: 'is-waterfall-chart', title: 'Waterfall Chart', category: 'data-viz', script: '../../components/charts/waterfall-chart.js', style: '../../components/charts/waterfall-chart.css', page: 'data-viz/is-waterfall-chart.html' },
  { tag: 'is-funnel-chart', title: 'Funnel Chart', category: 'data-viz', script: '../../components/charts/funnel-chart.js', style: '../../components/charts/funnel-chart.css', page: 'data-viz/is-funnel-chart.html' },
  { tag: 'is-class-diagram', title: 'Diagrama de clases', category: 'diagrams', script: '../../components/diagrams/class-diagram.js', style: '../../components/diagrams/class-diagram.css', page: 'diagrams/is-class-diagram.html' },
  { tag: 'is-state-diagram', title: 'Diagrama de estados', category: 'diagrams', script: '../../components/diagrams/state-diagram.js', style: '../../components/diagrams/state-diagram.css', page: 'diagrams/is-state-diagram.html' },
  { tag: 'is-er-diagram', title: 'Diagrama entidad-relación', category: 'diagrams', script: '../../components/diagrams/er-diagram.js', style: '../../components/diagrams/er-diagram.css', page: 'diagrams/is-er-diagram.html' },
  { tag: 'is-block-diagram', title: 'Diagrama de bloques', category: 'diagrams', script: '../../components/diagrams/block-diagram.js', style: '../../components/diagrams/block-diagram.css', page: 'diagrams/is-block-diagram.html' },
  { tag: 'is-treemap', title: 'Treemap', category: 'data-viz', script: '../../components/charts/treemap.js', style: '../../components/charts/treemap.css', page: 'data-viz/is-treemap.html' },
  { tag: 'is-mindmap', title: 'Mapa mental', category: 'diagrams', script: '../../components/diagrams/mindmap.js', style: '../../components/diagrams/mindmap.css', page: 'diagrams/is-mindmap.html' },
  { tag: 'is-gantt', title: 'Diagrama de Gantt', category: 'diagrams', script: '../../components/diagrams/gantt.js', style: '../../components/diagrams/gantt.css', page: 'diagrams/is-gantt.html' },
  { tag: 'is-timeline', title: 'Línea de tiempo', category: 'diagrams', script: '../../components/diagrams/timeline.js', style: '../../components/diagrams/timeline.css', page: 'diagrams/is-timeline.html' },
  { tag: 'is-fab', title: 'Floating Action Button', category: 'actions', script: '../../components/actions/fab.js', style: '../../components/actions/fab.css', page: 'actions/is-fab.html' },
  { tag: 'is-popconfirm', title: 'Popconfirm', category: 'feedback', script: '../../components/feedback/popconfirm.js', style: '../../components/feedback/popconfirm.css', page: 'feedback/is-popconfirm.html' },
  { tag: 'is-confirm-modal', title: 'Confirm Modal', category: 'feedback', script: '../../components/feedback/confirm-modal.js', style: '../../components/feedback/confirm-modal.css', page: 'feedback/is-confirm-modal.html' },
  { tag: 'is-pin-input', title: 'Pin Input', category: 'forms', script: '../../components/forms/pin-input.js', style: '../../components/forms/pin-input.css', page: 'forms/is-pin-input.html' },
  { tag: 'is-stat', title: 'Stat KPI', category: 'data', script: '../../components/data/stat.js', style: '../../components/data/stat.css', page: 'data/is-stat.html' },
  { tag: 'is-transfer', title: 'Transfer', category: 'data', script: '../../components/data/transfer.js', style: '../../components/data/transfer.css', page: 'data/is-transfer.html' },
  { tag: 'is-transfer-item', title: 'Transfer Item', category: 'data', script: '../../components/data/transfer.js', style: '../../components/data/transfer.css', page: 'data/is-transfer-item.html' },
  { tag: 'is-gauge', title: 'Gauge', category: 'data-viz', script: '../../components/data/gauge.js', style: '../../components/data/gauge.css', page: 'data-viz/is-gauge.html' },
  { tag: 'is-kanban', title: 'Kanban', category: 'data', script: '../../components/data/kanban.js', style: '../../components/data/kanban.css', page: 'data/is-kanban.html' },
  { tag: 'is-kanban-column', title: 'Kanban Column', category: 'data', script: '../../components/data/kanban.js', style: '../../components/data/kanban.css', page: 'data/is-kanban-column.html' },
  { tag: 'is-kanban-card', title: 'Kanban Card', category: 'data', script: '../../components/data/kanban.js', style: '../../components/data/kanban.css', page: 'data/is-kanban-card.html' },
  { tag: 'is-context-menu', title: 'Context Menu', category: 'actions', script: '../../components/actions/context-menu.js', style: '../../components/actions/context-menu.css', page: 'actions/is-context-menu.html' },
  { tag: 'is-speed-dial', title: 'Speed Dial', category: 'actions', script: '../../components/actions/speed-dial.js', style: '../../components/actions/speed-dial.css', page: 'actions/is-speed-dial.html' },
  { tag: 'is-speed-dial-action', title: 'Speed Dial Action', category: 'actions', script: '../../components/actions/speed-dial.js', style: '../../components/actions/speed-dial.css', page: 'actions/is-speed-dial-action.html' },
  { tag: 'is-barcode', title: 'Barcode', category: 'media', script: '../../components/media/barcode.js', style: '../../components/media/barcode.css', page: 'media/is-barcode.html' },
  { tag: 'is-image-editor', title: 'Image Editor', category: 'media', script: '../../components/media/image-editor.js', style: '../../components/media/image-editor.css', page: 'media/is-image-editor.html' },
  { tag: 'is-qrcode', title: 'QR Code', category: 'media', script: '../../components/media/qrcode.js', style: '../../components/media/qrcode.css', page: 'media/is-qrcode.html' },
  { tag: 'is-palette-selector', title: 'Palette Selector', category: 'feedback', script: '../../components/feedback/palette-selector.js', style: '../../components/feedback/palette-selector.css', page: 'feedback/is-palette-selector.html' },
  { tag: 'is-dock', title: 'Dock', category: 'layout', script: '../../components/layout/dock.js', style: '../../components/layout/dock.css', page: 'layout/is-dock.html' },
  { tag: 'is-dock-item', title: 'Dock Item', category: 'layout', script: '../../components/layout/dock.js', style: '../../components/layout/dock.css', page: 'layout/is-dock-item.html' },
  { tag: 'is-masked-input', title: 'Masked Input', category: 'forms', script: '../../components/forms/masked-input.js', style: '../../components/forms/masked-input.css', page: 'forms/is-masked-input.html' },
  { tag: 'is-inline-edit', title: 'Inline Edit', category: 'forms', script: '../../components/forms/inline-edit.js', style: '../../components/forms/inline-edit.css', page: 'forms/is-inline-edit.html' },
  { tag: 'is-mention', title: 'Mention', category: 'forms', script: '../../components/forms/mention.js', style: '../../components/forms/mention.css', page: 'forms/is-mention.html' },
  { tag: 'is-duration-picker', title: 'Duration Picker', category: 'forms', script: '../../components/forms/duration-picker.js', style: '../../components/forms/duration-picker.css', page: 'forms/is-duration-picker.html' },
  { tag: 'is-dropzone', title: 'Dropzone', category: 'forms', script: '../../components/forms/dropzone.js', style: '../../components/forms/dropzone.css', page: 'forms/is-dropzone.html' },
  { tag: 'is-full-calendar', title: 'Full Calendar', category: 'forms', script: '../../components/forms/full-calendar.js', style: '../../components/forms/full-calendar.css', page: 'forms/is-full-calendar.html' },
  { tag: 'is-signature', title: 'Signature', category: 'forms', script: '../../components/forms/signature.js', style: '../../components/forms/signature.css', page: 'forms/is-signature.html' },
  { tag: 'is-rte', title: 'Rich Text Editor', category: 'forms', script: '../../components/forms/rte.js', style: '../../components/forms/rte.css', page: 'forms/is-rte.html' },
  { tag: 'is-doc-editor', title: 'Document Editor', category: 'forms', script: '../../components/forms/doc-editor.js', style: '../../components/forms/doc-editor.css', page: 'forms/is-doc-editor.html' },
  { tag: 'is-mega-menu', title: 'Mega Menu', category: 'navigation', script: '../../components/navigation/mega-menu.js', style: '../../components/navigation/mega-menu.css', page: 'navigation/is-mega-menu.html' },
  { tag: 'is-pivot-table', title: 'Pivot Table', category: 'data', script: '../../components/data/pivot-table.js', style: '../../components/data/pivot-table.css', page: 'data/is-pivot-table.html' },
  { tag: 'is-spreadsheet', title: 'Spreadsheet', category: 'data', script: '../../components/data/spreadsheet.js', style: '../../components/data/spreadsheet.css', page: 'data/is-spreadsheet.html' },
  { tag: 'is-ag-grid', title: 'AG Grid', category: 'data', script: '../../components/data/ag-grid.js', style: '../../components/data/ag-grid.css', page: 'data/is-ag-grid.html' },
  { tag: 'is-heatmap', title: 'Heatmap', category: 'data-viz', script: '../../components/data-viz/heatmap.js', style: '../../components/data-viz/heatmap.css', page: 'data-viz/is-heatmap.html' },
  { tag: 'is-maps', title: 'Maps', category: 'data-viz', script: '../../components/data-viz/maps.js', style: '../../components/data-viz/maps.css', page: 'data-viz/is-maps.html' },
  { tag: 'is-map-marker', title: 'Map Marker', category: 'data-viz', script: '../../components/data-viz/maps.js', style: '../../components/data-viz/maps.css', page: 'data-viz/is-map-marker.html' },
  { tag: 'is-org-chart', title: 'Org Chart', category: 'diagrams', script: '../../components/diagrams/org-chart.js', style: '../../components/diagrams/org-chart.css', page: 'diagrams/is-org-chart.html' },
  { tag: 'is-command-palette', title: 'Command Palette', category: 'overlays', script: '../../components/overlays/command-palette.js', style: '../../components/overlays/command-palette.css', page: 'overlays/is-command-palette.html' },
  { tag: 'is-pdf-viewer', title: 'PDF Viewer', category: 'overlays', script: '../../components/overlays/pdf-viewer.js', style: '../../components/overlays/pdf-viewer.css', page: 'overlays/is-pdf-viewer.html' },
  { tag: 'is-window', title: 'Window', category: 'overlays', script: '../../components/overlays/window.js', style: '../../components/overlays/window.css', page: 'overlays/is-window.html' },
];
