/**
 * src/previews/_kit/component.schemas.ts — Canonical Zod schema for component JSONs.
 *
 * This is the SINGLE SOURCE OF TRUTH for the structure of every
 * `src/components/.../*.json` file (component preview definitions under
 * the `iswc-preview/v1` schema). Every component JSON in the repo MUST
 * validate against `ComponentJsonSchema` (with `.passthrough()` on every
 * level, so we tolerate custom fields without breaking the parser).
 *
 * ### Provenance
 *
 * - `PreviewDefinition` in `src/previews/_kit/types.d.ts` is the de-facto
 *   TS contract for these JSONs. This file expresses the same contract
 *   in Zod so we can run it at parse time (build, tests, audit).
 * - The structural rules in `src/utils/health/motor/validators/json-schema.ts`
 *   are the previous (hand-rolled) validation pass; the goal of W55 is to
 *   unify everything here so that there is only ONE schema definition.
 * - Fields appearing in real JSON files were inventoried with
 *   `src/utils/health/meta/w55-discover-json.mjs` (199 files scanned,
 *   198 are iswc-preview/v1 plus 1 diagram theme that uses a different
 *   `$schema`).
 *
 * ### Design decisions
 *
 * 1. **`.passthrough()` at every level.** Components may carry custom
 *    fields (e.g. an internal `ficha` block generated by the ficha
 *    bridge). We do not want to break those JSONs when we add a new
 *    field — we just want to flag what's missing or malformed.
 *
 * 2. **`html` / `code` / `lede` accept string | string[]** because the
 *    W43 refactor (limpieza de `\n` en JSON) converted multi-line
 *    text into arrays of lines. Consumers must pass through `asText()`
 *    (in `src/previews/_kit/text-like.ts`) to flatten them.
 *
 * 3. **Discriminated union on `kind`** for `BlockSchema` so the
 *    validator enforces per-kind required fields (`table.columns`,
 *    `demo.html`, `code.code`, etc.) without false positives.
 *
 * 4. **`BlockSchema` is exhaustive over the six documented kinds**
 *    (`demo`, `callout`, `code`, `html`, `table`, `lede`). If a new
 *    kind appears in JSON without being added here, the schema will
 *    reject it with a clear message — exactly what the test wants.
 *
 * 5. **`ComponentJsonSchema.passthrough()`** at the root lets us add
 *    fields (e.g. `ficha`, `examples`) without re-releasing the schema.
 *    Forward-compat by design.
 *
 * ### Out of scope
 *
 * - Diagram themes (`iswc-diagram-theme/v1`, currently only
 *   `src/components/diagrams/themes/insoft.json`) use a different
 *   `$schema` and a different shape. They're validated by the
 *   diagram-theme path, not by `ComponentJsonSchema`.
 */

import { z } from "zod";

/* ──────────────────────────────────────────────────────────────────────────
 * Primitives
 * ──────────────────────────────────────────────────────────────────────── */

/**
 * `TextLike` — texto que en el JSON puede venir como string o como array
 * de líneas (W43 refactor). Los consumidores deben pasar por `asText()`
 * para obtener un string único.
 */
export const TextLikeSchema = z.union([z.string(), z.array(z.string())]);

/* ──────────────────────────────────────────────────────────────────────────
 * Control (sub-bloque dentro de un demo.controls[])
 * ──────────────────────────────────────────────────────────────────────── */

/**
 * Una opción dentro de un control `select`. Puede ser un string simple
 * o un objeto {value,label,icon} para selects con icono.
 */
export const SelectOptionSchema = z.union([
  z.string(),
  z
    .object({
      value: z.string(),
      label: z.string(),
      icon: z.string().optional(),
    })
    .passthrough(),
]);

/**
 * Un control declarativo del playground (`controls[]` de un bloque demo).
 * Mínimo: `label` + `prop`. El resto son opcionales según el tipo.
 *
 *   { control: "select", prop: "attr:variant", label: "variant",
 *     options: ["filled","ghost",...] }
 */
export const ControlSchema = z
  .object({
    /** Tipo declarativo (text|select|boolean|number|range|color|json). */
    control: z.string().optional(),
    /** Path de la prop/atributo a aplicar al target (ej. `attr:variant`). */
    prop: z.string().optional(),
    /** Etiqueta visible para el usuario. */
    label: z.string().optional(),
    /** Opciones para `select` (strings u objetos {value,label,icon}). */
    options: z.array(SelectOptionSchema).optional(),
    /** Valor inicial (string). */
    default: z.union([z.string(), z.number(), z.boolean()]).optional(),
    /** Placeholder para inputs de texto. */
    placeholder: z.string().optional(),
    /** Agrupa varios controles bajo una sección visual. */
    group: z.string().optional(),
    /** Min/max/step para controles numéricos. */
    min: z.number().optional(),
    max: z.number().optional(),
    step: z.number().optional(),
  })
  .passthrough();

/* ──────────────────────────────────────────────────────────────────────────
 * Bloques (discriminated union por `kind`)
 * ──────────────────────────────────────────────────────────────────────── */

const HtmlBase = z.object({
  kind: z.string(),
  html: TextLikeSchema.optional(),
});

const DemoBlockSchema = z
  .object({
    kind: z.literal("demo"),
    /** Markup del ejemplo. */
    html: TextLikeSchema,
    /** Selector CSS del target dentro del demo (p. ej. `#btn-play`). */
    target: z.string().optional(),
    /** Controles del playground asociados al demo. */
    controls: z.array(ControlSchema).optional(),
    /** HTML equivalente nativo/ARIA (debajo del demo). */
    equivHtml: TextLikeSchema.optional(),
    /** Nota corta bajo el título de la sección equivalente. */
    equivNote: z.string().optional(),
    /** Markup opcional (p.ej. `<iswc-flowchart>`) que aclara ramas. */
    equivFlow: TextLikeSchema.optional(),
    /** Desactiva el botón "Ver código" del demo-code.js. */
    noCode: z.boolean().optional(),
    contain: z.boolean().optional(),
    heading: z.string().optional(),
  })
  .passthrough();

const CalloutBlockSchema = z
  .object({
    kind: z.literal("callout"),
    html: TextLikeSchema,
    tone: z.string().optional(),
    icon: z.string().optional(),
  })
  .passthrough();

const CodeBlockSchema = z
  .object({
    kind: z.literal("code"),
    code: TextLikeSchema,
    lang: z.string().optional(),
  })
  .passthrough();

const HtmlBlockSchema = z
  .object({
    kind: z.literal("html"),
    html: TextLikeSchema,
  })
  .passthrough();

const TableBlockSchema = z
  .object({
    kind: z.literal("table"),
    columns: z.array(z.string()),
    /** Cada fila es un array de celdas. Cada celda puede ser:
     *   - string (texto plano / HTML ligero)
     *   - array de strings (líneas múltiples, mismo patrón que `html`)
     *   - objeto (típicamente `code-ejemplo` o variantes)
     */
    rows: z.array(z.array(z.union([z.string(), z.array(z.string()), z.record(z.string(), z.unknown())]))),
    /** HTML opcional encima de la tabla. */
    captionHtml: TextLikeSchema.optional(),
    /** Clases extra del `<table>`. */
    className: z.string().optional(),
  })
  .passthrough();

const LedeBlockSchema = z
  .object({
    kind: z.literal("lede"),
    html: TextLikeSchema,
  })
  .passthrough();

/**
 * Unión discriminada por `kind`. Cualquier `kind` no declarado falla el
 * parseo con un mensaje claro — es la señal que el test busca.
 *
 * NOTA: usamos `z.discriminatedUnion` para que el runtime de Zod NO
 * intente parsear la unión completa cuando el `kind` ya no encaja.
 */
export const BlockSchema = z.discriminatedUnion("kind", [
  DemoBlockSchema,
  CalloutBlockSchema,
  CodeBlockSchema,
  HtmlBlockSchema,
  TableBlockSchema,
  LedeBlockSchema,
]);

/* ──────────────────────────────────────────────────────────────────────────
 * Sección (un grupo de bloques con encabezado propio)
 * ──────────────────────────────────────────────────────────────────────── */

/** Una sección del preview (`sections[]`). */
export const SectionSchema = z
  .object({
    /** Ancla única para TOC / scrollspy. */
    id: z.string().min(1),
    /** Título visible (etiqueta del TOC). */
    title: z.string().optional(),
    /** Si true, `title` se inserta como HTML (markup seguro). */
    titleHtml: z.boolean().optional(),
    /** Lede breve (markdown ligero / HTML escapado). */
    lede: TextLikeSchema.optional(),
    /** Elemento contenedor ('section' | 'aside'). */
    as: z.string().optional(),
    /** Clases del contenedor, además de `section`. */
    className: z.string().optional(),
    /** No pintar el <h2> del chrome. */
    hideTitle: z.boolean().optional(),
    /** `role` ARIA opcional. */
    role: z.string().optional(),
    ariaLabel: z.string().optional(),
    ariaLabelledby: z.string().optional(),
    /** Bloques que componen la sección. */
    blocks: z.array(BlockSchema),
  })
  .passthrough();

/* ──────────────────────────────────────────────────────────────────────────
 * Raíz del JSON (componente individual)
 * ──────────────────────────────────────────────────────────────────────── */

/**
 * Definición raíz de un componente (un archivo `src/components/.../*.json`).
 * Esta es la SCHEMA CANÓNICA: todo JSON de demo debe pasar por aquí.
 *
 * `.passthrough()` permite campos extra (ficha bridge, examples, etc.)
 * sin romper la validación.
 */
export const ComponentJsonSchema = z
  .object({
    /** Schema id — siempre "iswc-preview/v1" en JSON reales. */
    $schema: z.string().optional(),
    /** Tag del catálogo (manifest), p. ej. iswc-button. */
    tag: z.string().min(1),
    /** Categoría (carpeta bajo components/). */
    category: z.string().optional(),
    /** Título visible del H2 intro. */
    title: z.string().optional(),
    titleHtml: z.boolean().optional(),
    /** Descripción opcional (texto plano). */
    description: z.string().optional(),
    /** CSS local del preview (string o array de líneas W43). */
    styles: TextLikeSchema.optional(),
    /** Clave remember-scroll de iswc-main. */
    storageKey: z.string().optional(),
    /** Clases extra del `iswc-main` del chrome. */
    mainClass: z.string().optional(),
    /** Clase del contenedor que envuelve todas las secciones. */
    wrapperClass: z.string().optional(),
    /** HTML fijo antes del wrapper. */
    prelude: TextLikeSchema.optional(),
    /** Carga `behaviors/<tag>.js` (mount/unmount). */
    hasBehavior: z.boolean().optional(),
    /** No pintar TOC / panel derecho del split. */
    withoutToc: z.boolean().optional(),
    /** Secciones del componente. */
    sections: z.array(SectionSchema),
    /** Phase W21: presets tipados para `<iswc-examples-carousel>`. */
    examples: z.array(z.record(z.string(), z.unknown())).optional(),
    /** Sub-objeto ficha-bridge (sections + exclude + playground). */
    ficha: z
      .object({
        sections: z.record(z.string(), z.unknown()).optional(),
        exclude: z.array(z.string()).optional(),
        playground: z
          .object({
            html: z.string(),
            title: z.string().optional(),
            lede: z.string().optional(),
          })
          .passthrough()
          .optional(),
      })
      .passthrough()
      .optional(),
  })
  .passthrough();

/* ──────────────────────────────────────────────────────────────────────────
 * Tipos inferidos (compat con types.d.ts)
 * ──────────────────────────────────────────────────────────────────────── */

export type ComponentJson = z.infer<typeof ComponentJsonSchema>;
export type SectionJson = z.infer<typeof SectionSchema>;
export type BlockJson = z.infer<typeof BlockSchema>;
export type DemoBlockJson = z.infer<typeof DemoBlockSchema>;
export type CodeBlockJson = z.infer<typeof CodeBlockSchema>;
export type TableBlockJson = z.infer<typeof TableBlockSchema>;
export type HtmlBlockJson = z.infer<typeof HtmlBlockSchema>;
export type CalloutBlockJson = z.infer<typeof CalloutBlockSchema>;
export type LedeBlockJson = z.infer<typeof LedeBlockSchema>;
export type ControlJson = z.infer<typeof ControlSchema>;
export type TextLike = z.infer<typeof TextLikeSchema>;

/* ──────────────────────────────────────────────────────────────────────────
 * Tipos derivados (compat con PreviewDefinition de types.d.ts)
 * ──────────────────────────────────────────────────────────────────────── */

/** El `kind` de bloque aceptado por la spec `iswc-preview/v1`. */
export type BlockKind = BlockJson["kind"];

/** Los seis kinds documentados. Útil para tests y para uniones. */
export const BLOCK_KINDS = [
  "demo",
  "callout",
  "code",
  "html",
  "table",
  "lede",
] as const satisfies readonly BlockKind[];